readers_writers:
	@rm -f readers_writers.out
	@gcc readers_writers.c -lpthread -o readers_writers.out
	@./readers_writers.out

philosophers:
	@rm -f philosophers.out
	@gcc philosophers.c -lpthread -o philosophers.out
	@./philosophers.out

clean:
	@rm *.out